### ISSUE TITLE
Error installing starter kit

### ISSUE THREAD

**Issue by espenlg** [joschuba/statamic-vite#4]
I wanted to try this today, but ended up with an error I'm afraid. Is it related to Statamic 3.4?

![Screenshot 2023-01-31 at 17 00 48](https://user-images.githubusercontent.com/1135679/215813071-07bac8f0-edc7-4fb3-80a2-8e227c3c5935.png)

**Comment by joschuba** [comment]
@espenlg I think you have just a little typo. It has to be `joschuba/statamic-vite` in the install command, instead of `joschuba/vite`. So run `statamic new mysite joschuba/statamic-vite` and you're ready to go – with Statamic 3.4, too. :)

**Comment by espenlg** [comment]
Thank you! I wasn't sure so I copied the starter-kit name from the URL :)

**Comment by joschuba** [comment]
You're welcome, happy asset bundling with Vite! :)
